---
# Playbook to display the running version on Cisco IOS Devices

- name: Display running version on Cisco IOS devices
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts from Cisco devices
      cisco.ios.ios_facts:
      register: facts

    - name: Display all gathered facts
      debug:
        var: facts

    - name: Display running version
      debug:
        msg: "Current version is {{ facts.ansible_facts.ansible_net_version }}"

    - name: Send email
      community.general.mail:
        host: smtp.mail.me.com
        port: 587
        username: {{ mail_user }}
        password: {{ mail_password }}
        to: "ajidom@gmail.com"
        from: "cfwong@me.com"
        subject: "AWX report"
        body: |
          Test email
      delegate_to: localhost
      run_once: true
