---
# Playbook to display the running version on Cisco IOS Devices

- name: Display running version on Cisco IOS devices
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts from Cisco devices
      cisco.ios.ios_facts:
      register: facts

    - name: Display all gathered facts
      debug:
        var: facts

    - name: Display running version
      debug:
        msg: "Current version is {{ facts.ansible_facts.ansible_net_version }}"

    - name: Send email
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}" 
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "ajidom@gmail.com"
        from: "gary.wong@garywong.pro"
        subject: "AWX report"
        body: |
          Test email
      delegate_to: localhost
      run_once: true
